project:
  type: website

website:
  title: "Ununderstanding Pheno"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - icon: github
        href: https://github.com/HenFar/physblog

format:
  html:
    theme:
      - journal
    css: styles.css
    toc: true



